apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-zfs-local-dataset-provisioner
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: "0.14.x"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-repo
      interval: 12h
  # https://github.com/democratic-csi/democratic-csi/tree/master/examples
  values:
    csiDriver:
      name: "org.democratic-csi.zfs-local-dataset"
      attachRequired: false
      storageCapacity: true # With storage capacity tracking, the scheduler filters out nodes which do not have enough capacity.
      fsGroupPolicy: File # fsGroupChangePolicy
    driver:
      config:
        driver: zfs-local-dataset
        zfs:
          datasetParentName: nvme/k8s/v
          detachedSnapshotsDatasetParentName: nvme/k8s/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetProperties:
            compression: lz4
            atime: off
            overlay: on
