apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: "0.14.x"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-repo
      interval: 12h
  # https://github.com/democratic-csi/democratic-csi/tree/master/examples
  values:
    csiDriver:
      name: nvme-csi

    driver: zfs-local-dataset

    zfs:
      datasetParentName: nvme/k8s/volumes
      detachedSnapshotsDatasetParentName: nvme/k8s/snapshots

      datasetEnableQuotas: true
      datasetEnableReservation: false
