apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: system-controllers
namespace: kube-system

resources:
- cert-manager
- config-syncer
- democratic-csi
- sealed-secrets
- secret-generator
- traefik
