apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: gitea-creds
spec:
  forceRegenerate: true
  data:
    username: admin-y45hfw542
  fields:
  - fieldName: password
    encoding: base64
    length: '32'
