apiVersion: v1
kind: Secret
metadata:
  name: dex-client-gitea
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    secret-generator.v1.mittwald.de/encoding: base64
    secret-generator.v1.mittwald.de/autogenerate: secret
type: Opaque
stringData:
  key: gitea
