apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: dex-repo
      interval: 12h
  values:

    serviceMonitor:
      enabled: false

    config:
      issuer: https://dex.catboy.rest
      storage:
        type: kubernetes
        config:
          inCluster: true
      oauth2:
        skipApprovalScreen: true
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          redirectURI: https://dex.catboy.rest/callback
          loadAllGroups: true
          teamNameField: slug
          useLoginAsID: false
          orgs:
          - name: CozyDen
            teams:
            - Admin
            - User
      staticClients:
      - id: gitea
        redirectURIs:
        - https://gitea.catboy.rest/user/oauth2/Dex/callback
        name: Gitea

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - host: dex.catboy.rest
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - dex.catboy.rest
        secretName: dex-cert

  valuesFrom:
  - kind: Secret
    name: github-oauth
    valuesKey: client-id
    targetPath: config.connectors[0].config.clientID
    optional: false
  - kind: Secret
    name: github-oauth
    valuesKey: client-secret
    targetPath: config.connectors[0].config.clientSecret
    optional: false
  - kind: Secret
    name: dex-clients
    valuesKey: gitea
    targetPath: config.staticClients[0].secret
    optional: false
