apiVersion: v1
kind: Secret
metadata:
  name: dex-values
type: Opaque
stringData:
  values: >

    serviceMonitor:
      enabled: false

    config:
      issuer: https://dex.catboy.rest
      storage:
        type: kubernetes
        config:
          inCluster: true
      oauth2:
        skipApprovalScreen: true
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          redirectURI: https://dex.catboy.rest/callback
          loadAllGroups: true
          teamNameField: both
          useLoginAsID: false
          orgs:
          - name: CozyDen
            teams:
            - Admin
            - User
      staticClients:
      - name: Gitea
        redirectURIs:
        - https://gitea.catboy.rest/user/oauth2/Dex/callback

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - host: dex.catboy.rest
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - dex.catboy.rest
        secretName: dex-cert
