apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed
spec:
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      # Number of retries that should be attempted on failures before bailing, a negative integer equals to unlimited retries
      retries: -1
  chart:
    spec:
      chart: kubed
      version: "0.13.2"
      sourceRef:
        kind: HelmRepository
        name: kubed-repo
      interval: 12h
