apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: whoami-creds
spec:
  forceRegenerate: false
  data:
    username: user
  fields:
  - fieldName: password
    encoding: base64
    length: '32'
