apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: config-syncer
spec:
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      # Number of retries that should be attempted on failures before bailing, a negative integer equals to unlimited retries
      retries: -1
  chart:
    spec:
      chart: config-syncer
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: config-syncer-repo
      interval: 12h
  # https://github.com/kubeops/installer/blob/master/charts/config-syncer/values.yaml
  valuesFrom:
  - kind: Secret
    name: config-syncer-license
    valuesKey: license
    targetPath: license
    optional: false
