apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: config-syncer
spec:
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      # Number of retries that should be attempted on failures before bailing, a negative integer equals to unlimited retries
      retries: -1
  chart:
    spec:
      chart: config-syncer
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: config-syncer-repo
      interval: 12h
  # https://github.com/kubeops/installer/blob/master/charts/config-syncer/values.yaml
  values:
    license: |
      ----BEGIN CERTIFICATE-----
      MIIEUjCCAzqgAwIBAgIIOcFjYESc94wwDQYJKoZIhvcNAQELBQAwJTEWMBQGA1UE
      ChMNQXBwc0NvZGUgSW5jLjELMAkGA1UEAxMCY2EwHhcNMjQwNjAyMjIwNjM0WhcN
      MjQwNzAyMjIwNjM0WjCCARgxDzANBgNVBAYTBmt1YmVkYjETMBEGA1UECBMKZW50
      ZXJwcmlzZTGBpDAXBgNVBAoTEGt1YmVkYi1jb21tdW5pdHkwFwYDVQQKExBrdWJl
      ZGItZXh0LXN0YXNoMBgGA1UEChMRa3ViZWRiLWF1dG9zY2FsZXIwGAYDVQQKExFr
      dWJlZGItZW50ZXJwcmlzZTAcBgNVBAoTFXBhbm9wdGljb24tZW50ZXJwcmlzZTAe
      BgNVBAoTF2t1YmVkYi1tb25pdG9yaW5nLWFnZW50MRowGAYDVQQLExFrdWJlZGIt
      ZW50ZXJwcmlzZTEtMCsGA1UEAxMkMDQ5NTUxNmQtMmVjNS00NzdjLWFlNjctNTQy
      OWZkNTBjZWExMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2rmJtAZy
      CjrrQsDKJ8ztorJsp5xZ3Sa1ZH2baJXNFMNRm0+mF0w7kHRpYlvIyG3Zf4zpqERs
      +FQJY4AxVVhY9yLQC9Im6zhzER9p+EKhzoSpQ7DObzG+ODkK0pXU2ZJ9UtHnKk/k
      7u+gF5Wk4TSUJpBw+a8k/ytWOIc1h6F3uvvqU8nqd4tvoAZiioVwUQWOEm+ab804
      b5yUGYOS8N0B7bry4baIdNAgIiOSI20nAXnm3eMYKlWL/m+SwKSyx2mn1MTgrkS9
      TVQ1dEXsqgmpiAuO491UMcHskJorDTJ4GB8PH0jKa1Zzc51Q2rpGUf/EH15meaiB
      E3L89t5RXWFnFwIDAQABo4GQMIGNMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
      BggrBgEFBQcDAjBmBgNVHREEXzBdgiQwNDk1NTE2ZC0yZWM1LTQ3N2MtYWU2Ny01
      NDI5ZmQ1MGNlYTGBHlR3aW5raSA8dGhldHdpbmtlaGhAZ21haWwuY29tPoEVdGhl
      dHdpbmtlaGhAZ21haWwuY29tMA0GCSqGSIb3DQEBCwUAA4IBAQBOYoG77aQB8lwT
      T2w+uEfkFhwxd1LmKsasrdEqNIqX6a11m+Oe8eRdxZBudHfTuWzjEx8bSqnrHCzI
      lId6IUfiuEgJZNm/Yj1ijWKfQ2xYiwmChB+ob9imwc7QIO3xFiIJa29r+5Gsh9HL
      RgfdK1Wt0TvZAAl2US34vTbyI8DYgBafitOxX1NRULtKLPHGSn/OTPp4/cJyFpy7
      fUq6fHYLkFcMhq2U19zFa47dB8IPOUY9KYBHVjD+VsTQ4vSo//ghhw5+5zSm13AC
      Js9j0zqlt9BLEQB+YIMsD2sAXTXTGs1srkQbYu8DHdRt0F37ie+B3wCdsiF29Aub
      1lf63lWW
      -----END CERTIFICATE-----
